--------------------------------------------------------------------------------
-- 로컬 개발용 초기화 스크립트. 운영에서는 절대 쓰지 않는다.
-- FK 역순으로 내린다. 아직 없는 테이블은 ORA-00942 가 나지만 무시해도 된다.
--------------------------------------------------------------------------------
DROP TABLE TEAM_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE REFRESH_TOKEN CASCADE CONSTRAINTS;
DROP TABLE MISSION_MODE_VOTE_BALLOT CASCADE CONSTRAINTS;
DROP TABLE MISSION_MODE_VOTE CASCADE CONSTRAINTS;
DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE REACTION CASCADE CONSTRAINTS;
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE TRANSACTIONS CASCADE CONSTRAINTS;
DROP TABLE MISSION_LOG CASCADE CONSTRAINTS;
DROP TABLE DAILY_MISSION_ASSIGNMENT CASCADE CONSTRAINTS;
DROP TABLE MISSION CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE MEMBER_NOTIFICATION_SETTING CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE CHALLENGE CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
