--------------------------------------------------------------------------------
-- 2026-08-25 (2) 마이그레이션 — 요구사항정의서 v0.4 §4 "계속 미정" 4건 구현분
--
--   ① FR-008  미션 방식 팀원 투표        → MISSION_MODE_VOTE / MISSION_MODE_VOTE_BALLOT 신설
--   ② FR-012c 방장 무응답 자동 승인      → MISSION_LOG.REVIEW_REQUESTED_AT 신설, REVIEWED_BY 에 'AUTO' 허용
--   ③ FR-035  리프레시 토큰 정책         → REFRESH_TOKEN 신설
--   ④ 카카오 연동 해제                   → 스키마 변경 없음(FR-043 계정 탈퇴 처리를 그대로 재사용)
--
-- schema-oracle.sql 은 새로 만드는 DB 용이고 이 파일은 이미 만들어진 DB 를 따라잡게 한다.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- ① 미션 방식 팀원 투표 (FR-008)
--   방장이 단독으로 정하던 MISSION_MODE 를 팀원 투표로 정할 수 있게 한다.
--   확정 결과는 CHALLENGE.MISSION_MODE 에 그대로 반영되므로, 투표는 "결정 과정"만 남긴다.
--------------------------------------------------------------------------------
CREATE TABLE MISSION_MODE_VOTE (
    ID                   NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    CHALLENGE_ID         NUMBER(19)   NOT NULL,
    STATUS               VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,   -- OPEN / CLOSED
    DEADLINE             TIMESTAMP    NOT NULL,                  -- 지나면 조회·투표 시점에 자동 마감된다
    -- 마감 결과. DECIDED(다수결 확정) / TIE(동률) / NOT_ENOUGH_VOTES(정족수 미달)
    OUTCOME              VARCHAR2(20),
    RESULT_MODE          VARCHAR2(10),                           -- DECIDED 일 때만. FIXED / AI
    OPENED_BY_MEMBER_ID  NUMBER(19)   NOT NULL,
    CREATED_AT           TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CLOSED_AT            TIMESTAMP,
    CONSTRAINT PK_MISSION_MODE_VOTE PRIMARY KEY (ID),
    CONSTRAINT FK_MMV_CHALLENGE FOREIGN KEY (CHALLENGE_ID) REFERENCES CHALLENGE (ID),
    CONSTRAINT FK_MMV_OPENED_BY FOREIGN KEY (OPENED_BY_MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT CK_MMV_STATUS CHECK (STATUS IN ('OPEN', 'CLOSED')),
    CONSTRAINT CK_MMV_OUTCOME CHECK (OUTCOME IN ('DECIDED', 'TIE', 'NOT_ENOUGH_VOTES')),
    CONSTRAINT CK_MMV_RESULT_MODE CHECK (RESULT_MODE IN ('FIXED', 'AI')),
    -- 열려 있는 동안에는 결과가 없고, 닫히면 결과가 있어야 한다
    CONSTRAINT CK_MMV_CLOSED_HAS_OUTCOME CHECK (
        (STATUS = 'OPEN'   AND OUTCOME IS NULL AND CLOSED_AT IS NULL)
        OR (STATUS = 'CLOSED' AND OUTCOME IS NOT NULL AND CLOSED_AT IS NOT NULL))
);

-- 챌린지당 열린 투표는 하나뿐이다. 닫힌 것은 이력으로 얼마든지 쌓인다.
-- (부분 인덱스가 없는 Oracle 에서는 CASE 식으로 같은 효과를 낸다 — OPEN 이 아닌 행은 NULL 이라 제외된다.)
CREATE UNIQUE INDEX UX_MMV_OPEN_PER_CHALLENGE
    ON MISSION_MODE_VOTE (CASE WHEN STATUS = 'OPEN' THEN CHALLENGE_ID END);

CREATE INDEX IX_MMV_CHALLENGE ON MISSION_MODE_VOTE (CHALLENGE_ID, ID DESC);

--------------------------------------------------------------------------------
-- MISSION_MODE_VOTE_BALLOT : 한 사람이 한 투표에 한 표.
--   마음을 바꾸면 새 행이 아니라 CHOICE 를 갱신한다(PK 가 재투표를 막아준다).
--------------------------------------------------------------------------------
CREATE TABLE MISSION_MODE_VOTE_BALLOT (
    VOTE_ID   NUMBER(19)   NOT NULL,
    MEMBER_ID NUMBER(19)   NOT NULL,
    CHOICE    VARCHAR2(10) NOT NULL,                             -- FIXED / AI
    VOTED_AT  TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MMV_BALLOT PRIMARY KEY (VOTE_ID, MEMBER_ID),
    CONSTRAINT FK_MMVB_VOTE FOREIGN KEY (VOTE_ID) REFERENCES MISSION_MODE_VOTE (ID),
    CONSTRAINT FK_MMVB_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT CK_MMVB_CHOICE CHECK (CHOICE IN ('FIXED', 'AI'))
);

--------------------------------------------------------------------------------
-- ② 방장 무응답 자동 승인 (FR-012c)
--   "언제부터 방장을 기다리고 있는가"를 알아야 기한 경과를 잴 수 있다.
--   DISPUTE_REQUESTED / RECHECK_REQUESTED / RESUBMITTED 로 들어갈 때 서비스가 채운다.
--------------------------------------------------------------------------------
ALTER TABLE MISSION_LOG ADD (REVIEW_REQUESTED_AT TIMESTAMP);

-- 자동 승인은 사람이 판정한 것이 아니므로 판정 주체를 구분한다. 프론트는 이 값으로 라벨을 가른다.
ALTER TABLE MISSION_LOG DROP CONSTRAINT CK_MISSION_LOG_REVIEWED_BY;
ALTER TABLE MISSION_LOG ADD CONSTRAINT CK_MISSION_LOG_REVIEWED_BY
    CHECK (REVIEWED_BY IN ('AI', 'OWNER', 'AUTO'));

--------------------------------------------------------------------------------
-- ③ 리프레시 토큰 (FR-035)
--   원문은 저장하지 않고 SHA-256 해시만 둔다 — DB 가 새도 토큰을 재현할 수 없어야 한다.
--   회전(rotation) 방식이라 재발급 때마다 이전 토큰을 폐기하고 새 행을 만든다.
--------------------------------------------------------------------------------
CREATE TABLE REFRESH_TOKEN (
    ID         NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    USER_ID    NUMBER(19)    NOT NULL,
    TOKEN_HASH VARCHAR2(64)  NOT NULL,                           -- SHA-256 hex
    EXPIRES_AT TIMESTAMP     NOT NULL,
    REVOKED_AT TIMESTAMP,                                        -- NULL 이면 살아 있는 토큰
    CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REFRESH_TOKEN PRIMARY KEY (ID),
    CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT UK_REFRESH_TOKEN_HASH UNIQUE (TOKEN_HASH)
);

-- 로그아웃·계정탈퇴·재사용 감지에서 한 사용자의 토큰을 통째로 폐기할 때 쓴다.
CREATE INDEX IX_REFRESH_TOKEN_USER ON REFRESH_TOKEN (USER_ID, REVOKED_AT);
