--------------------------------------------------------------------------------
-- 2026-08-25 (3) 마이그레이션 — FR-044 팀 응원 메시지 (1:N)
--
-- 팀원 누구나 챌린지 팀 전체에 한 줄 응원을 보낸다. 실시간 채팅(MVP 제외)이 아니라
-- 단건 발송이고, 받는 쪽은 기존 알림함(화면 15)에서 그대로 읽는다.
--
-- 알림(NOTIFICATION)만으로도 "보내기"는 되지만 테이블을 따로 둔 이유는 세 가지다.
--   * 발신자를 알아야 한다 — NOTIFICATION 에는 수신자만 있고 보낸 사람 컬럼이 없다.
--   * 도배를 막으려면 "이 사람이 오늘 몇 번 보냈나"를 세야 한다.
--   * 알림은 사람 수만큼 복제되지만 메시지 원본은 하나여야 한다(수정·삭제·목록의 기준).
--------------------------------------------------------------------------------
CREATE TABLE TEAM_MESSAGE (
    ID               NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
    CHALLENGE_ID     NUMBER(19)       NOT NULL,
    SENDER_MEMBER_ID NUMBER(19)       NOT NULL,
    -- 다른 테이블은 바이트 기준이지만 여기만 글자 기준이다. 한글 200자를 그대로 받아야 하는데
    -- VARCHAR2(200) 이면 바이트 기준이라 67자에서 잘린다.
    CONTENT          VARCHAR2(200 CHAR) NOT NULL,
    CREATED_AT       TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TEAM_MESSAGE PRIMARY KEY (ID),
    CONSTRAINT FK_TEAM_MESSAGE_CHALLENGE FOREIGN KEY (CHALLENGE_ID) REFERENCES CHALLENGE (ID),
    CONSTRAINT FK_TEAM_MESSAGE_SENDER FOREIGN KEY (SENDER_MEMBER_ID) REFERENCES MEMBER (ID)
);

-- 목록 조회(커서 페이지네이션)는 최신순이다.
CREATE INDEX IX_TEAM_MESSAGE_CHALLENGE ON TEAM_MESSAGE (CHALLENGE_ID, ID DESC);

-- 하루 발송 횟수 제한을 셀 때 쓴다.
CREATE INDEX IX_TEAM_MESSAGE_SENDER ON TEAM_MESSAGE (SENDER_MEMBER_ID, CREATED_AT);
