--------------------------------------------------------------------------------
-- 같이 모으기 — Oracle DDL (v0.4 + API 명세서 정렬)
-- 출처: Notion "요구사항정의서0.4" §5 + "API 명세서" DB 37개 엔드포인트의 요청/응답 스펙
--
-- 명명 규칙
--   * USER / COMMENT 는 Oracle 예약어라 USERS / COMMENTS 로 복수형을 쓴다.
--     TRANSACTION 도 충돌 소지가 있어 TRANSACTIONS 로 통일했다.
--     그 외에는 단수형이다. Notion 문서는 복수형(MEMBERS 등)으로 적혀 있으나 테이블명은
--     API 계약에 노출되지 않으므로 이 파일의 기존 규칙을 유지했다.
--   * enum 값은 API 명세서의 응답 예시를 정답으로 삼는다. DB 값과 JSON 값이 같아야
--     서비스 계층에서 변환할 일이 없다.
--   * boolean 은 CHAR(1) 'Y'/'N'. JSON 에서는 true/false 로 내려간다.
--   * 컬럼명은 API 필드명과 맞췄다(submitContent, attachmentUrl, rejectReasonCode 등).
--     map-underscore-to-camel-case 로 그대로 매핑되게 하기 위함이다.
--
-- API 명세서 반영으로 v0.4 최초안에서 바뀐 것
--   * MEMBER.ROLE      LEADER → OWNER
--   * MEMBER.STATUS    INVITED/JOINED/LEFT → ACTIVE/LEFT  ([확인필요] 아래 참고)
--   * TRANSACTIONS.TX_TYPE  PAYOUT/CLAWBACK/REPAYOUT → MISSION_REWARD/REVERSAL/RE_PAYMENT
--   * REACTION 제약     멤버당 이모지별 1개 → 멤버당 1개 (다른 타입 누르면 교체)
--   * CHALLENGE.MISSION_MODE  NOT NULL DEFAULT 'FIXED' → nullable (생성 직후 null, 이후 설정)
--   * MISSION 에서 DIFFICULTY / DESCRIPTION / SOURCE_TYPE 제거 (어떤 응답에도 없음)
--   * 보상 금액이 고정값 → 범위로 변경 (claude 컨텍스트 §12, 2026-08-20)
--     MISSION.REWARD_AMOUNT → REWARD_MIN/REWARD_MAX,
--     DAILY_MISSION_ASSIGNMENT.REWARD_AMOUNT 신설(배정 시점에 한 번만 추첨)
--   * 컬럼명 정렬: PROOF_TYPE→SUBMIT_TYPE, MIN_LENGTH→MIN_TEXT_LENGTH,
--                  CONTENT→SUBMIT_CONTENT, PHOTO_URL→ATTACHMENT_URL,
--                  MISDETECT_REASON_CODE→REJECT_REASON_CODE, EMOJI_TYPE→REACTION_TYPE,
--                  NOTIFICATION.MESSAGE→CONTENT
--
-- 2026-08-25 추가
--   * USERS.WITHDRAWN_AT 신설 — FR-043 계정 탈퇴(DELETE /users/me)
--   * 캘린더(FR-027/FR-040)·스트릭(FR-025)은 기존 테이블 집계라 스키마 변경이 없다
--   * 이미 만들어진 DB 는 migration-2026-08-25.sql 로 따라잡는다
--
-- 2026-08-25 (2) 추가 — 요구사항정의서 v0.4 §4 "계속 미정" 4건 구현분
--   * MISSION_MODE_VOTE / MISSION_MODE_VOTE_BALLOT 신설 — FR-008 미션 방식 팀원 투표
--   * MISSION_LOG.REVIEW_REQUESTED_AT 신설, REVIEWED_BY 에 AUTO 허용 — FR-012c 무응답 자동 승인
--   * REFRESH_TOKEN 신설 — FR-035 리프레시 토큰
--   * 이미 만들어진 DB 는 migration-2026-08-25-open-issues.sql 로 따라잡는다
--
-- 2026-08-25 (3) 추가
--   * TEAM_MESSAGE 신설 — FR-044 팀 응원 메시지(1:N). migration-2026-08-25-team-message.sql
--   * TEAM_MESSAGE.UPDATED_AT/DELETED_AT + IX_NOTIFICATION_TARGET — 메시지 수정·삭제
--     (migration-2026-08-25-team-message-edit.sql)
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- USERS : 카카오 로그인으로 생성되는 전역 계정 (FR-030)
--------------------------------------------------------------------------------
CREATE TABLE USERS (
    ID              NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    KAKAO_ID        VARCHAR2(64) NOT NULL,
    EMAIL           VARCHAR2(255),
    TERMS_AGREED_AT TIMESTAMP,                                   -- FR-028 약관 동의 일시
    TERMS_VERSION   VARCHAR2(20),                                -- FR-028 동의한 약관 버전
    CREATED_AT      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    -- FR-043 계정 탈퇴. NULL 이면 활성 계정. 행을 지우지 않는 이유는 MEMBER 를 참조하는
    -- 과거 기록(미션 로그·거래·댓글)이 남아야 하기 때문이다. 탈퇴 시 KAKAO_ID 는
    -- 'withdrawn:'||ID 로, EMAIL 은 NULL 로 치환한다(개인정보 파기 + 같은 카카오 계정 재가입 허용).
    WITHDRAWN_AT    TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_KAKAO_ID UNIQUE (KAKAO_ID)
);

--------------------------------------------------------------------------------
-- CHALLENGE : 챌린지 (FR-001, FR-007, FR-036)
--   MISSION_MODE 는 생성 시점에 정하지 않는다. POST /challenges 응답이 null 을 내려주고,
--   방장이 PATCH /challenges/{id}/mission-mode 로 나중에 설정한다.
--------------------------------------------------------------------------------
CREATE TABLE CHALLENGE (
    ID            NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    TITLE         VARCHAR2(100) NOT NULL,
    TARGET_AMOUNT NUMBER(15)    NOT NULL,                        -- API 필드명은 goalAmount
    START_DATE    DATE          NOT NULL,
    END_DATE      DATE          NOT NULL,
    INVITE_CODE   VARCHAR2(20)  NOT NULL,
    MISSION_MODE  VARCHAR2(10),                                  -- FIXED / AI. 미설정이면 NULL
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CHALLENGE PRIMARY KEY (ID),
    CONSTRAINT UK_CHALLENGE_INVITE_CODE UNIQUE (INVITE_CODE),
    CONSTRAINT CK_CHALLENGE_MISSION_MODE CHECK (MISSION_MODE IN ('FIXED', 'AI')),
    CONSTRAINT CK_CHALLENGE_PERIOD CHECK (END_DATE >= START_DATE),
    CONSTRAINT CK_CHALLENGE_TARGET_AMOUNT CHECK (TARGET_AMOUNT > 0)
);

--------------------------------------------------------------------------------
-- MEMBER : 챌린지별 참여 정보 (FR-003, FR-004, FR-006)
--   방장 정보의 유일한 소스는 이 테이블의 ROLE 이다. 방장 양도는 CHALLENGE 를 건드리지 않고
--   ROLE UPDATE 2건으로 처리한다.
--
--   [확인필요] STATUS 에서 INVITED 가 빠졌다. API 명세서에는 ACTIVE / LEFT 만 등장하는데,
--     요구사항 FR-004/FR-006 의 "초대됨(읽기 전용)" 상태가 폐지된 것인지 명세에서 누락된
--     것인지 불명확하다. 명세를 따라 두 값만 허용한다.
--------------------------------------------------------------------------------
CREATE TABLE MEMBER (
    ID           NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    USER_ID      NUMBER(19)   NOT NULL,
    CHALLENGE_ID NUMBER(19)   NOT NULL,
    NICKNAME     VARCHAR2(30) NOT NULL,
    ROLE         VARCHAR2(10) DEFAULT 'MEMBER' NOT NULL,         -- OWNER(방장) / MEMBER(팀원)
    STATUS       VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,         -- ACTIVE / LEFT(탈퇴, FR-038)
    THEME_COLOR  VARCHAR2(20),                                   -- FR-041 캘린더 색상(개인 설정, 예 '#18A8F1')
    -- 알림 수신 설정은 종류별로 켜고 끌 수 있어야 해서 MEMBER_NOTIFICATION_SETTING 으로 분리했다.
    JOINED_AT    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (ID),
    CONSTRAINT FK_MEMBER_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_MEMBER_CHALLENGE FOREIGN KEY (CHALLENGE_ID) REFERENCES CHALLENGE (ID),
    CONSTRAINT UK_MEMBER_USER_CHALLENGE UNIQUE (USER_ID, CHALLENGE_ID),
    CONSTRAINT UK_MEMBER_CHALLENGE_NICKNAME UNIQUE (CHALLENGE_ID, NICKNAME),
    CONSTRAINT CK_MEMBER_ROLE CHECK (ROLE IN ('OWNER', 'MEMBER')),
    CONSTRAINT CK_MEMBER_STATUS CHECK (STATUS IN ('ACTIVE', 'LEFT'))
);

CREATE INDEX IX_MEMBER_USER ON MEMBER (USER_ID);

--------------------------------------------------------------------------------
-- MEMBER_NOTIFICATION_SETTING : 챌린지별·종류별 알림 수신 설정 (개인 설정)
--   컬럼을 종류마다 늘리는 대신 행으로 뒀다. 알림 종류가 아직 확정 전이라 늘거나 줄 수 있는데,
--   그때마다 DDL 을 고치지 않아도 되게 하려는 것이다.
--
--   행이 없으면 '켜짐'으로 본다. 끈 것만 저장하므로 새 종류가 생겨도 백필이 필요 없고,
--   기본이 수신인 정책과도 맞는다.
--
--   NOTI_TYPE 에 CHECK 를 걸지 않은 이유는 NOTIFICATION.NOTI_TYPE 과 같다 — 목록 미확정.
--------------------------------------------------------------------------------
CREATE TABLE MEMBER_NOTIFICATION_SETTING (
    MEMBER_ID NUMBER(19)   NOT NULL,
    NOTI_TYPE VARCHAR2(30) NOT NULL,
    ENABLED   CHAR(1)      DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_MEMBER_NOTI_SETTING PRIMARY KEY (MEMBER_ID, NOTI_TYPE),
    CONSTRAINT FK_MNS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT CK_MNS_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);

--------------------------------------------------------------------------------
-- ACCOUNT : 가상 계좌 (FR-017) — Member 와 1:1
--   잔액 갱신은 트리거가 아니라 서비스가 TRANSACTIONS INSERT 와 같은 트랜잭션에서
--   AccountMapper.addBalance 로 처리한다.
--------------------------------------------------------------------------------
CREATE TABLE ACCOUNT (
    ID        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    MEMBER_ID NUMBER(19) NOT NULL,
    BALANCE   NUMBER(15) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID),
    CONSTRAINT FK_ACCOUNT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT UK_ACCOUNT_MEMBER UNIQUE (MEMBER_ID),
    CONSTRAINT CK_ACCOUNT_BALANCE CHECK (BALANCE >= 0)
);

--------------------------------------------------------------------------------
-- MISSION : 미션 마스터 (FR-007 ~ FR-010)
--   방장이 직접 만들거나(CREATED_BY_TYPE='OWNER') AI 제안을 골라 등록한다('AI').
--   AI 생성 API 는 제안만 돌려주고 저장하지 않으므로, 저장 시점에는 항상 방장이 개입한다.
--
--   [확인필요] CHALLENGE_ID 를 nullable 로 남겨 전역 고정 풀 시드를 유지했다. API 명세서의
--     미션 엔드포인트는 전부 챌린지 하위라, 전역 풀을 폐지하고 NOT NULL 로 바꿔야 할 수도 있다.
--------------------------------------------------------------------------------
CREATE TABLE MISSION (
    ID                   NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    CHALLENGE_ID         NUMBER(19),                             -- NULL = 전역 공용 고정 풀
    TITLE                VARCHAR2(200) NOT NULL,
    SUBMIT_TYPE          VARCHAR2(10)  DEFAULT 'TEXT' NOT NULL,  -- TEXT / PHOTO
    -- 보상은 고정값이 아니라 범위다(FR-013 100~10,000원 균등 랜덤).
    -- 실제 금액은 배정 시점에 이 범위 안에서 한 번 뽑아 DAILY_MISSION_ASSIGNMENT 에 저장한다.
    REWARD_MIN           NUMBER(7),
    REWARD_MAX           NUMBER(7),
    MIN_TEXT_LENGTH      NUMBER(5),                              -- TEXT 미션 자동완료 기준. PHOTO 면 NULL
    CREATED_BY_TYPE      VARCHAR2(10),                           -- OWNER / AI. 전역 고정 풀은 NULL
    CREATED_BY_MEMBER_ID NUMBER(19),                             -- AI 생성도 등록한 방장을 남긴다
    IS_ACTIVE            CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_MISSION PRIMARY KEY (ID),
    CONSTRAINT FK_MISSION_CHALLENGE FOREIGN KEY (CHALLENGE_ID) REFERENCES CHALLENGE (ID),
    CONSTRAINT FK_MISSION_CREATED_BY FOREIGN KEY (CREATED_BY_MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT CK_MISSION_SUBMIT_TYPE CHECK (SUBMIT_TYPE IN ('TEXT', 'PHOTO')),
    CONSTRAINT CK_MISSION_CREATED_BY_TYPE CHECK (CREATED_BY_TYPE IN ('OWNER', 'AI')),
    CONSTRAINT CK_MISSION_REWARD_RANGE CHECK (
        REWARD_MIN >= 100 AND REWARD_MAX <= 10000 AND REWARD_MIN <= REWARD_MAX),
    CONSTRAINT CK_MISSION_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE INDEX IX_MISSION_CHALLENGE ON MISSION (CHALLENGE_ID, IS_ACTIVE);

--------------------------------------------------------------------------------
-- DAILY_MISSION_ASSIGNMENT : 오늘의 미션 배정 (FR-010)
--   챌린지당 하루 1건. GET /challenges/{id}/missions/today 최초 호출 시 서버가 랜덤 배정을
--   생성하고, 이후 호출은 같은 행을 돌려준다.
--
--   REWARD_AMOUNT 는 배정 시점에 MISSION.REWARD_MIN~REWARD_MAX 에서 균등 랜덤으로 한 번만
--   뽑아 고정한다. 같은 날·같은 챌린지의 멤버는 모두 같은 금액을 받는다 — 함께 수행하는
--   미션인데 보상이 다르면 팀 안에서 불공정하게 느껴지기 때문이다.
--   이 값은 today 응답에 담지 않는다(범위만 노출). 미션 완료 후 화면 12에서 처음 공개된다.
--------------------------------------------------------------------------------
CREATE TABLE DAILY_MISSION_ASSIGNMENT (
    ID            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    CHALLENGE_ID  NUMBER(19) NOT NULL,
    MISSION_ID    NUMBER(19) NOT NULL,
    ASSIGNED_DATE DATE       NOT NULL,
    REWARD_AMOUNT NUMBER(7)  NOT NULL,                           -- 배정 시점에 확정된 금액
    CREATED_AT    TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DAILY_MISSION_ASSIGNMENT PRIMARY KEY (ID),
    CONSTRAINT FK_DMA_CHALLENGE FOREIGN KEY (CHALLENGE_ID) REFERENCES CHALLENGE (ID),
    CONSTRAINT FK_DMA_MISSION FOREIGN KEY (MISSION_ID) REFERENCES MISSION (ID),
    CONSTRAINT UK_DMA_CHALLENGE_DATE UNIQUE (CHALLENGE_ID, ASSIGNED_DATE),
    CONSTRAINT CK_DMA_REWARD CHECK (REWARD_AMOUNT BETWEEN 100 AND 10000)
);

--------------------------------------------------------------------------------
-- MISSION_LOG : 미션 수행 기록 (FR-011 ~ FR-016)
--   하루 1미션 제한은 UK_MISSION_LOG_MEMBER_ASSIGNMENT 가 보장한다(배정 자체가 하루 1건).
--   중복 제출 시 이 제약 위반 → 409.
--
--   상태 흐름 (FR-012, 8단계)
--     SUBMITTED ──AI판정──> AI_APPROVED
--                       └─> AI_REJECTED ──이의제기──> DISPUTE_REQUESTED
--                                                  ├─> RECHECK_REQUESTED (그대로 재검토)
--                                                  └─> RESUBMITTED       (수정 후 재제출)
--                                                        └─방장판정─> OWNER_APPROVED / OWNER_REJECTED
--------------------------------------------------------------------------------
CREATE TABLE MISSION_LOG (
    ID                 NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    MEMBER_ID          NUMBER(19)   NOT NULL,
    ASSIGNMENT_ID      NUMBER(19)   NOT NULL,
    SUBMIT_CONTENT     CLOB,                                     -- 텍스트 미션 작성 내용
    ATTACHMENT_URL     VARCHAR2(500),                            -- 사진 미션 증빙 경로
    -- 완료 처리 시 DAILY_MISSION_ASSIGNMENT.REWARD_AMOUNT 를 복사해 넣는다
    REWARD_AMOUNT      NUMBER(7),
    IS_PUBLIC          CHAR(1)      DEFAULT 'Y' NOT NULL,        -- FR-015 기본값 공개
    STATUS             VARCHAR2(20) NOT NULL,
    REVIEWED_BY        VARCHAR2(10),                             -- 마지막 판정 주체. AI / OWNER
    REJECT_REASON_CODE VARCHAR2(20),                             -- 반려 사유. 없으면 NULL
    RESUBMIT_COUNT     NUMBER(3)    DEFAULT 0 NOT NULL,          -- FR-012b
    -- 방장 판정을 기다리기 시작한 시각(FR-012c). 무응답 자동 승인 기한을 여기서 잰다.
    REVIEW_REQUESTED_AT TIMESTAMP,
    COMPLETED_AT       TIMESTAMP,
    CREATED_AT         TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MISSION_LOG PRIMARY KEY (ID),
    CONSTRAINT FK_MISSION_LOG_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT FK_MISSION_LOG_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID)
        REFERENCES DAILY_MISSION_ASSIGNMENT (ID),
    CONSTRAINT UK_MISSION_LOG_MEMBER_ASSIGNMENT UNIQUE (MEMBER_ID, ASSIGNMENT_ID),
    CONSTRAINT CK_MISSION_LOG_IS_PUBLIC CHECK (IS_PUBLIC IN ('Y', 'N')),
    CONSTRAINT CK_MISSION_LOG_STATUS CHECK (
        STATUS IN ('SUBMITTED',
                   'AI_APPROVED', 'AI_REJECTED',
                   'DISPUTE_REQUESTED',
                   'RECHECK_REQUESTED', 'RESUBMITTED',
                   'OWNER_APPROVED', 'OWNER_REJECTED')),
    -- AUTO = 방장이 기한 내에 판정하지 않아 자동 승인된 건(FR-012c)
    CONSTRAINT CK_MISSION_LOG_REVIEWED_BY CHECK (REVIEWED_BY IN ('AI', 'OWNER', 'AUTO')),
    -- 화질불량 / 조도부족 / 주제무관 / 기타
    CONSTRAINT CK_MISSION_LOG_REASON CHECK (
        REJECT_REASON_CODE IN ('LOW_QUALITY', 'LOW_LIGHT', 'IRRELEVANT', 'ETC')),
    CONSTRAINT CK_MISSION_LOG_REWARD CHECK (REWARD_AMOUNT BETWEEN 100 AND 10000)
);

CREATE INDEX IX_MISSION_LOG_MEMBER ON MISSION_LOG (MEMBER_ID, CREATED_AT DESC);
CREATE INDEX IX_MISSION_LOG_ASSIGNMENT ON MISSION_LOG (ASSIGNMENT_ID);
CREATE INDEX IX_MISSION_LOG_STATUS ON MISSION_LOG (STATUS);

--------------------------------------------------------------------------------
-- TRANSACTIONS : 입금 기록 (FR-017, FR-018, FR-012d)
--   REVERSAL(취소) / RE_PAYMENT(재지급)은 ORIGINAL_TRANSACTION_ID 로 원거래를 가리킨다.
--   사용자가 직접 호출하는 API 는 없고 재판정 로직 내부에서만 생성된다.
--------------------------------------------------------------------------------
CREATE TABLE TRANSACTIONS (
    ID                      NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    ACCOUNT_ID              NUMBER(19)   NOT NULL,
    MISSION_LOG_ID          NUMBER(19)   NOT NULL,
    ORIGINAL_TRANSACTION_ID NUMBER(19),                          -- REVERSAL / RE_PAYMENT 일 때만 값 존재
    AMOUNT                  NUMBER(15)   NOT NULL,               -- REVERSAL 은 음수
    TX_TYPE                 VARCHAR2(20) NOT NULL,               -- MISSION_REWARD / REVERSAL / RE_PAYMENT
    CREATED_AT              TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (ID),
    CONSTRAINT FK_TRANSACTIONS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID),
    CONSTRAINT FK_TRANSACTIONS_MISSION_LOG FOREIGN KEY (MISSION_LOG_ID) REFERENCES MISSION_LOG (ID),
    CONSTRAINT FK_TRANSACTIONS_ORIGINAL FOREIGN KEY (ORIGINAL_TRANSACTION_ID) REFERENCES TRANSACTIONS (ID),
    CONSTRAINT CK_TRANSACTIONS_TX_TYPE CHECK (
        TX_TYPE IN ('MISSION_REWARD', 'REVERSAL', 'RE_PAYMENT'))
);

CREATE INDEX IX_TRANSACTIONS_ACCOUNT ON TRANSACTIONS (ACCOUNT_ID, CREATED_AT DESC);
CREATE INDEX IX_TRANSACTIONS_MISSION_LOG ON TRANSACTIONS (MISSION_LOG_ID);

--------------------------------------------------------------------------------
-- NOTIFICATION : 알림 (FR-020, FR-021, FR-012a)
--   TARGET_TYPE + TARGET_ID 다형 참조. DB 레벨 FK 를 걸 수 없으므로 대상 존재 보장은 서비스 몫.
--
--   [확인필요] NOTI_TYPE / TARGET_TYPE 에 CHECK 를 걸지 않았다. API 명세서가 예시로
--     MISSION_REWARD, MISSION_LOG/CHALLENGE "등"만 들고 전체 목록을 정의하지 않아,
--     지금 제약을 걸면 정의되지 않은 정상 값을 거부하게 된다. 목록 확정 후 CHECK 추가할 것.
--------------------------------------------------------------------------------
CREATE TABLE NOTIFICATION (
    ID                 NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    RECEIVER_MEMBER_ID NUMBER(19)    NOT NULL,
    NOTI_TYPE          VARCHAR2(30)  NOT NULL,                   -- 예: MISSION_REWARD (API 필드명은 type)
    CONTENT            VARCHAR2(500),                            -- 알림 문구
    TARGET_TYPE        VARCHAR2(30),                             -- 예: MISSION_LOG / CHALLENGE
    TARGET_ID          NUMBER(19),
    IS_READ            CHAR(1)       DEFAULT 'N' NOT NULL,
    CREATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY (ID),
    CONSTRAINT FK_NOTIFICATION_RECEIVER FOREIGN KEY (RECEIVER_MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT CK_NOTIFICATION_IS_READ CHECK (IS_READ IN ('Y', 'N')),
    -- 대상 타입과 ID 는 항상 함께 있거나 함께 없어야 한다
    CONSTRAINT CK_NOTIFICATION_TARGET_PAIR CHECK (
        (TARGET_TYPE IS NULL AND TARGET_ID IS NULL)
        OR (TARGET_TYPE IS NOT NULL AND TARGET_ID IS NOT NULL))
);

-- 폴링 기반 알림함 조회(FR-021) / 미확인 개수 조회용
CREATE INDEX IX_NOTIFICATION_RECEIVER ON NOTIFICATION (RECEIVER_MEMBER_ID, IS_READ, CREATED_AT DESC);

--------------------------------------------------------------------------------
-- REACTION : 이모지 리액션 (FR-022)
--   멤버당 미션기록 1개만 남길 수 있다. 같은 타입을 다시 누르면 삭제(토글 해제),
--   다른 타입을 누르면 기존 걸 지우고 교체한다.
--------------------------------------------------------------------------------
CREATE TABLE REACTION (
    ID               NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    MISSION_LOG_ID   NUMBER(19)   NOT NULL,
    SENDER_MEMBER_ID NUMBER(19)   NOT NULL,
    REACTION_TYPE    VARCHAR2(20) NOT NULL,                      -- 예: CLAP / FIRE
    CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REACTION PRIMARY KEY (ID),
    CONSTRAINT FK_REACTION_MISSION_LOG FOREIGN KEY (MISSION_LOG_ID) REFERENCES MISSION_LOG (ID),
    CONSTRAINT FK_REACTION_SENDER FOREIGN KEY (SENDER_MEMBER_ID) REFERENCES MEMBER (ID),
    -- 멤버당 1개. 이모지 타입은 제약에 포함하지 않는다.
    CONSTRAINT UK_REACTION_LOG_SENDER UNIQUE (MISSION_LOG_ID, SENDER_MEMBER_ID)
);

--------------------------------------------------------------------------------
-- COMMENTS : 댓글 (FR-023) — 공개된 미션 상세에 작성. 삭제는 작성자 본인만.
--------------------------------------------------------------------------------
CREATE TABLE COMMENTS (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    MISSION_LOG_ID   NUMBER(19) NOT NULL,
    SENDER_MEMBER_ID NUMBER(19) NOT NULL,
    CONTENT          CLOB       NOT NULL,
    CREATED_AT       TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_COMMENTS PRIMARY KEY (ID),
    CONSTRAINT FK_COMMENTS_MISSION_LOG FOREIGN KEY (MISSION_LOG_ID) REFERENCES MISSION_LOG (ID),
    CONSTRAINT FK_COMMENTS_SENDER FOREIGN KEY (SENDER_MEMBER_ID) REFERENCES MEMBER (ID)
);

CREATE INDEX IX_COMMENTS_MISSION_LOG ON COMMENTS (MISSION_LOG_ID, CREATED_AT);

--------------------------------------------------------------------------------
-- ① 미션 방식 팀원 투표 (FR-008)
--   방장이 단독으로 정하던 MISSION_MODE 를 팀원 투표로 정할 수 있게 한다.
--   확정 결과는 CHALLENGE.MISSION_MODE 에 그대로 반영되므로, 투표는 "결정 과정"만 남긴다.
--------------------------------------------------------------------------------
CREATE TABLE MISSION_MODE_VOTE (
    ID                   NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    CHALLENGE_ID         NUMBER(19)   NOT NULL,
    STATUS               VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,   -- OPEN / CLOSED
    DEADLINE             TIMESTAMP    NOT NULL,                  -- 지나면 조회·투표 시점에 자동 마감된다
    -- 마감 결과. DECIDED(다수결 확정) / TIE(동률) / NOT_ENOUGH_VOTES(정족수 미달)
    OUTCOME              VARCHAR2(20),
    RESULT_MODE          VARCHAR2(10),                           -- DECIDED 일 때만. FIXED / AI
    OPENED_BY_MEMBER_ID  NUMBER(19)   NOT NULL,
    CREATED_AT           TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CLOSED_AT            TIMESTAMP,
    CONSTRAINT PK_MISSION_MODE_VOTE PRIMARY KEY (ID),
    CONSTRAINT FK_MMV_CHALLENGE FOREIGN KEY (CHALLENGE_ID) REFERENCES CHALLENGE (ID),
    CONSTRAINT FK_MMV_OPENED_BY FOREIGN KEY (OPENED_BY_MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT CK_MMV_STATUS CHECK (STATUS IN ('OPEN', 'CLOSED')),
    CONSTRAINT CK_MMV_OUTCOME CHECK (OUTCOME IN ('DECIDED', 'TIE', 'NOT_ENOUGH_VOTES')),
    CONSTRAINT CK_MMV_RESULT_MODE CHECK (RESULT_MODE IN ('FIXED', 'AI')),
    -- 열려 있는 동안에는 결과가 없고, 닫히면 결과가 있어야 한다
    CONSTRAINT CK_MMV_CLOSED_HAS_OUTCOME CHECK (
        (STATUS = 'OPEN'   AND OUTCOME IS NULL AND CLOSED_AT IS NULL)
        OR (STATUS = 'CLOSED' AND OUTCOME IS NOT NULL AND CLOSED_AT IS NOT NULL))
);

-- 챌린지당 열린 투표는 하나뿐이다. 닫힌 것은 이력으로 얼마든지 쌓인다.
-- (부분 인덱스가 없는 Oracle 에서는 CASE 식으로 같은 효과를 낸다 — OPEN 이 아닌 행은 NULL 이라 제외된다.)
CREATE UNIQUE INDEX UX_MMV_OPEN_PER_CHALLENGE
    ON MISSION_MODE_VOTE (CASE WHEN STATUS = 'OPEN' THEN CHALLENGE_ID END);

CREATE INDEX IX_MMV_CHALLENGE ON MISSION_MODE_VOTE (CHALLENGE_ID, ID DESC);

--------------------------------------------------------------------------------
-- MISSION_MODE_VOTE_BALLOT : 한 사람이 한 투표에 한 표.
--   마음을 바꾸면 새 행이 아니라 CHOICE 를 갱신한다(PK 가 재투표를 막아준다).
--------------------------------------------------------------------------------
CREATE TABLE MISSION_MODE_VOTE_BALLOT (
    VOTE_ID   NUMBER(19)   NOT NULL,
    MEMBER_ID NUMBER(19)   NOT NULL,
    CHOICE    VARCHAR2(10) NOT NULL,                             -- FIXED / AI
    VOTED_AT  TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MMV_BALLOT PRIMARY KEY (VOTE_ID, MEMBER_ID),
    CONSTRAINT FK_MMVB_VOTE FOREIGN KEY (VOTE_ID) REFERENCES MISSION_MODE_VOTE (ID),
    CONSTRAINT FK_MMVB_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
    CONSTRAINT CK_MMVB_CHOICE CHECK (CHOICE IN ('FIXED', 'AI'))
);


--------------------------------------------------------------------------------
-- ③ 리프레시 토큰 (FR-035)
--   원문은 저장하지 않고 SHA-256 해시만 둔다 — DB 가 새도 토큰을 재현할 수 없어야 한다.
--   회전(rotation) 방식이라 재발급 때마다 이전 토큰을 폐기하고 새 행을 만든다.
--------------------------------------------------------------------------------
CREATE TABLE REFRESH_TOKEN (
    ID         NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    USER_ID    NUMBER(19)    NOT NULL,
    TOKEN_HASH VARCHAR2(64)  NOT NULL,                           -- SHA-256 hex
    EXPIRES_AT TIMESTAMP     NOT NULL,
    REVOKED_AT TIMESTAMP,                                        -- NULL 이면 살아 있는 토큰
    CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REFRESH_TOKEN PRIMARY KEY (ID),
    CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT UK_REFRESH_TOKEN_HASH UNIQUE (TOKEN_HASH)
);

-- 로그아웃·계정탈퇴·재사용 감지에서 한 사용자의 토큰을 통째로 폐기할 때 쓴다.
CREATE INDEX IX_REFRESH_TOKEN_USER ON REFRESH_TOKEN (USER_ID, REVOKED_AT);

--------------------------------------------------------------------------------
-- TEAM_MESSAGE : 팀 응원 메시지 (FR-044) — 팀원 누구나 팀 전체에 한 줄 보낸다.
--   실시간 채팅(MVP 제외)이 아니라 단건 발송이고, 받는 쪽은 알림함에서 읽는다.
--   NOTIFICATION 만으로 안 되는 이유는 발신자·도배 카운트·원본 하나 유지 셋이다.
--------------------------------------------------------------------------------
CREATE TABLE TEAM_MESSAGE (
    ID               NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
    CHALLENGE_ID     NUMBER(19)       NOT NULL,
    SENDER_MEMBER_ID NUMBER(19)       NOT NULL,
    -- 다른 테이블은 바이트 기준이지만 여기만 글자 기준이다. 한글 200자를 그대로 받아야 하는데
    -- VARCHAR2(200) 이면 바이트 기준이라 67자에서 잘린다.
    CONTENT          VARCHAR2(200 CHAR) NOT NULL,
    CREATED_AT       TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    -- 수정·삭제 시각. 삭제는 soft delete 다 — 알림함에서는 흔적 없이 사라지지만(알림 행은 실제로
    -- 지운다) 원본은 남겨, 지우고 다시 보내는 식으로 하루 발송 한도를 우회하지 못하게 한다.
    UPDATED_AT       TIMESTAMP,
    DELETED_AT       TIMESTAMP,
    CONSTRAINT PK_TEAM_MESSAGE PRIMARY KEY (ID),
    CONSTRAINT FK_TEAM_MESSAGE_CHALLENGE FOREIGN KEY (CHALLENGE_ID) REFERENCES CHALLENGE (ID),
    CONSTRAINT FK_TEAM_MESSAGE_SENDER FOREIGN KEY (SENDER_MEMBER_ID) REFERENCES MEMBER (ID)
);

-- 목록 조회(커서 페이지네이션)는 최신순이다.
CREATE INDEX IX_TEAM_MESSAGE_CHALLENGE ON TEAM_MESSAGE (CHALLENGE_ID, ID DESC);

-- 하루 발송 횟수 제한을 셀 때 쓴다.
CREATE INDEX IX_TEAM_MESSAGE_SENDER ON TEAM_MESSAGE (SENDER_MEMBER_ID, CREATED_AT);

-- 원본 하나로 알림 여러 건을 되짚어 갈 때 쓴다(메시지 수정·삭제가 알림을 따라가야 해서).
CREATE INDEX IX_NOTIFICATION_TARGET ON NOTIFICATION (TARGET_TYPE, TARGET_ID);
